[package]
name = "command"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.5.2"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.4.18", features = ["derive"] }
async-trait = "0.1.77"
lazy_static = { version = "1.4.0"}
once_cell = "1.19.0"
tracing = "0.1.37"

[[bin]]
name = "main"
path = "bin/main.rs"
